defmodule Exhub.KuriDaemon do
  @moduledoc """
  Supervised daemon that auto-starts the `kuri` HTTP server binary via Exile.

  Kuri is a Zig-based browser automation server that manages a Chrome instance
  via CDP and exposes an HTTP API (tabs, navigate, snapshot, action, etc.).
  This GenServer ensures kuri is running whenever Exhub boots, providing the
  browser backend for `kuri-agent` and the BrowserUse MCP tools.

  ## Robustness Features

  - **Deep health checks**: Verifies both HTTP liveness (`/health`) and Chrome/CDP
    functionality (`/tabs` with auth). Detects "zombie" state where kuri is up but
    Chrome is dead.
  - **Auto-recovery**: After 3 consecutive failed deep checks, kills and restarts kuri.
  - **Exponential backoff**: Restart delay grows 5s → 10s → 20s → 40s (cap 60s),
    resets on successful startup.
  - **Proper process management**: Tracks the OS pid via Exile port for clean SIGTERM.

  ## Duplicate Server Prevention

  Before starting a new kuri server, the daemon checks if a server is already
  running on the configured host:port. If a healthy kuri server is detected,
  the daemon will skip starting a new process and use the existing one instead.

  ## Configuration (application env)

  | Key                 | Default                         | Description                        |
  |---------------------|---------------------------------|------------------------------------|
  | `:kuri_enabled`     | `true`                          | Enable/disable the daemon          |
  | `:kuri_port`        | `18080`                         | HTTP listen port                   |
  | `:kuri_host`        | `"127.0.0.1"`                   | Bind address                       |
  | `:kuri_headless`    | `true`                          | Run Chrome headless                |
  | `:kuri_binary`      | `nil` (auto-detect)             | Explicit path to `kuri` binary     |

  ## Binary resolution order

  1. `:kuri_binary` application env (if set)
  2. `System.find_executable("kuri")` (PATH)
  3. `~/Code/kuri/zig-out/bin/kuri` (local dev build)
  """

  use GenServer
  require Logger

  @default_port 18080
  @default_host "127.0.0.1"
  @health_check_interval_ms 30_000
  @base_restart_delay_ms 5_000
  @max_restart_delay_ms 60_000
  @startup_timeout_ms 15_000
  @startup_poll_interval_ms 500
  @max_consecutive_failures 3

  # ── Client API ──────────────────────────────────────────────────────────────

  def start_link(opts \\ []) do
    GenServer.start_link(__MODULE__, opts, name: __MODULE__)
  end

  @doc "Returns `:healthy`, `:degraded`, `:unhealthy`, `:starting`, `:disabled`, or `:stopped`."
  def status do
    GenServer.call(__MODULE__, :status)
  end

  @doc "Returns the base URL of the running kuri server, e.g. `\"http://127.0.0.1:18080\"`."
  def base_url do
    GenServer.call(__MODULE__, :base_url)
  end

  @doc "Performs a synchronous deep health check (HTTP + CDP)."
  def health do
    GenServer.call(__MODULE__, :health, 15_000)
  end

  @doc """
  Returns the kuri API token for authenticating HTTP requests.

  Resolution order:
  1. `KURI_API_TOKEN` env var
  2. `KURI_SECRET` env var (legacy)
  3. `~/.kuri/api.token` file (auto-generated by kuri on first launch)
  """
  def api_token do
    System.get_env("KURI_API_TOKEN") ||
      System.get_env("KURI_SECRET") ||
      read_token_file() ||
      ""
  end

  # ── Server callbacks ────────────────────────────────────────────────────────

  @impl true
  def init(_opts) do
    # Ensure :inets is started for :httpc (health checks)
    :inets.start()
    :ssl.start()

    port = Application.get_env(:exhub, :kuri_port, @default_port)
    host = Application.get_env(:exhub, :kuri_host, @default_host)
    headless = Application.get_env(:exhub, :kuri_headless, true)
    enabled = Application.get_env(:exhub, :kuri_enabled, true)

    state = %{
      port: port,
      host: host,
      headless: headless,
      status: :stopped,
      binary: nil,
      daemon_ref: nil,
      daemon_pid: nil,
      os_pid: nil,
      health_timer: nil,
      restart_timer: nil,
      consecutive_failures: 0,
      restart_count: 0
    }

    if enabled do
      case resolve_binary() do
        nil ->
          Logger.warning(
            "[KuriDaemon] `kuri` binary not found — daemon disabled. " <>
              "Install kuri or set :exhub, :kuri_binary in config."
          )

          {:ok, %{state | status: :disabled}}

        binary ->
          Logger.info("[KuriDaemon] Found kuri binary at #{binary}")
          send(self(), :start_daemon)
          {:ok, %{state | status: :starting, binary: binary}}
      end
    else
      Logger.info("[KuriDaemon] Disabled via :exhub, :kuri_enabled = false")
      {:ok, %{state | status: :disabled}}
    end
  end

  @impl true
  def handle_call(:status, _from, state) do
    {:reply, state.status, state}
  end

  def handle_call(:base_url, _from, state) do
    {:reply, "http://#{state.host}:#{state.port}", state}
  end

  def handle_call(:health, _from, state) do
    result = deep_health_check(state.host, state.port)
    {:reply, result, state}
  end

  @impl true
  def handle_info(:start_daemon, state) do
    Logger.info("[KuriDaemon] Starting kuri server on #{state.host}:#{state.port}...")

    # Check if a server is already running on this port
    case check_existing_server(state.host, state.port) do
      {:ok, _body} ->
        Logger.info(
          "[KuriDaemon] ✓ kuri server already running at http://#{state.host}:#{state.port}"
        )

        timer = schedule_health_check()
        {:noreply, %{state | status: :healthy, health_timer: timer, consecutive_failures: 0}}

      {:error, {:port_in_use, status}} ->
        Logger.warning(
          "[KuriDaemon] Port #{state.port} is in use but returned status #{status}. " <>
            "Proceeding with caution — may conflict with existing service."
        )

        start_new_daemon(state)

      {:error, :no_server} ->
        start_new_daemon(state)
    end
  end

  def handle_info({ref, result}, %{daemon_ref: ref} = state) when is_reference(ref) do
    # Daemon process completed (kuri exited)
    Process.demonitor(ref, [:flush])
    Logger.warning("[KuriDaemon] kuri process exited: #{inspect(result)}")

    schedule_restart(state)
  end

  def handle_info({:DOWN, ref, :process, _pid, reason}, %{daemon_ref: ref} = state) do
    Logger.warning("[KuriDaemon] kuri process crashed: #{inspect(reason)}")

    schedule_restart(state)
  end

  def handle_info(:health_check, state) do
    {new_status, new_failures} =
      case deep_health_check(state.host, state.port) do
        {:ok, :full} ->
          {:healthy, 0}

        {:ok, :http_only} ->
          # HTTP is up but Chrome/CDP is dead — degraded
          {:degraded, state.consecutive_failures + 1}

        {:error, _} ->
          {:unhealthy, state.consecutive_failures + 1}
      end

    if new_status != state.status do
      Logger.info("[KuriDaemon] Health status changed: #{state.status} → #{new_status}")
    end

    # Auto-restart after too many consecutive failures
    if new_failures >= @max_consecutive_failures and state.daemon_pid do
      Logger.warning(
        "[KuriDaemon] #{new_failures} consecutive failures — restarting kuri daemon"
      )

      kill_daemon(state)
      timer = Process.send_after(self(), :start_daemon, restart_delay(state.restart_count))

      {:noreply,
       %{
         state
         | status: :stopped,
           daemon_ref: nil,
           daemon_pid: nil,
           os_pid: nil,
           health_timer: nil,
           restart_timer: timer,
           consecutive_failures: 0,
           restart_count: state.restart_count + 1
       }}
    else
      timer = schedule_health_check()
      {:noreply, %{state | status: new_status, health_timer: timer, consecutive_failures: new_failures}}
    end
  end

  defp start_new_daemon(state) do
    env = build_env(state)

    {pid, ref} =
      spawn_monitor(fn ->
        run_kuri(state.binary, env)
      end)

    # Wait for kuri to become healthy
    case wait_for_startup(state.host, state.port) do
      :ok ->
        Logger.info("[KuriDaemon] ✓ kuri server is healthy at http://#{state.host}:#{state.port}")
        timer = schedule_health_check()

        {:noreply,
         %{
           state
           | status: :healthy,
             daemon_ref: ref,
             daemon_pid: pid,
             health_timer: timer,
             consecutive_failures: 0,
             restart_count: 0
         }}

      :timeout ->
        Logger.warning(
          "[KuriDaemon] kuri started but health check timed out after #{@startup_timeout_ms}ms"
        )

        timer = schedule_health_check()

        {:noreply,
         %{
           state
           | status: :unhealthy,
             daemon_ref: ref,
             daemon_pid: pid,
             health_timer: timer
         }}
    end
  end

  @impl true
  def terminate(_reason, state) do
    cancel_timer(state.health_timer)
    cancel_timer(state.restart_timer)
    kill_daemon(state)
    :ok
  end

  # ── Private helpers ─────────────────────────────────────────────────────────

  defp resolve_binary do
    explicit = Application.get_env(:exhub, :kuri_binary)

    dev_path = Path.join([System.user_home!(), "Code", "kuri", "zig-out", "bin", "kuri"])

    cond do
      is_binary(explicit) and File.exists?(explicit) ->
        explicit

      path = System.find_executable("kuri") ->
        path

      File.exists?(dev_path) ->
        dev_path

      true ->
        nil
    end
  end

  defp build_env(state) do
    base = [
      {"HOST", state.host},
      {"PORT", Integer.to_string(state.port)},
      {"HEADLESS", to_string(state.headless)}
    ]

    # Filter out nil values from env
    Enum.reject(base, fn {_k, v} -> v == "nil" or v == "" end)
  end

  defp run_kuri(binary, env) do
    Logger.info("[KuriDaemon] Executing: #{binary}")

    Exile.stream([binary], env: env, stderr: :consume)
    |> Enum.reduce(:ok, fn
      {:stdout, data}, acc ->
        data
        |> String.trim()
        |> String.split("\n")
        |> Enum.each(fn line -> Logger.debug("[kuri] #{line}") end)

        acc

      {:stderr, data}, acc ->
        data
        |> String.trim()
        |> String.split("\n")
        |> Enum.each(fn line -> Logger.warning("[kuri:err] #{line}") end)

        acc

      {:exit, {:status, code}}, _acc ->
        Logger.warning("[kuri] Process exited with status #{code}")
        {:exit, code}

      {:exit, :epipe}, _acc ->
        Logger.info("[kuri] Process exited (epipe)")
        {:exit, 0}

      _event, acc ->
        acc
    end)
  end

  defp wait_for_startup(host, port, elapsed \\ 0) do
    if elapsed >= @startup_timeout_ms do
      :timeout
    else
      case do_http_health_check(host, port) do
        {:ok, _} ->
          :ok

        _ ->
          Process.sleep(@startup_poll_interval_ms)
          wait_for_startup(host, port, elapsed + @startup_poll_interval_ms)
      end
    end
  end

  @doc false
  # Deep health check: verifies HTTP liveness AND Chrome/CDP functionality.
  # Returns:
  #   {:ok, :full}       — both HTTP and CDP are working
  #   {:ok, :http_only}  — HTTP is up but CDP/Chrome is dead (degraded)
  #   {:error, reason}   — HTTP is unreachable
  defp deep_health_check(host, port) do
    case do_http_health_check(host, port) do
      {:ok, _body} ->
        # HTTP is up — now verify Chrome/CDP via /tabs
        case do_tabs_check(host, port) do
          {:ok, _tabs} -> {:ok, :full}
          {:error, _} -> {:ok, :http_only}
        end

      {:error, reason} ->
        {:error, reason}
    end
  end

  defp do_http_health_check(host, port) do
    url = "http://#{host}:#{port}/health"

    case :httpc.request(:get, {to_charlist(url), []}, [timeout: 5_000], body_format: :binary) do
      {:ok, {{_, 200, _}, _headers, body}} ->
        {:ok, body}

      {:ok, {{_, status, _}, _headers, body}} ->
        {:error, {:http_error, status, body}}

      {:error, reason} ->
        {:error, reason}
    end
  end

  # Checks /tabs endpoint with auth to verify Chrome/CDP is functional.
  defp do_tabs_check(host, port) do
    url = "http://#{host}:#{port}/tabs"
    token = api_token()
    headers = [{~c"authorization", to_charlist("Bearer #{token}")}]

    case :httpc.request(:get, {to_charlist(url), headers}, [timeout: 5_000], body_format: :binary) do
      {:ok, {{_, 200, _}, _headers, body}} ->
        {:ok, body}

      {:ok, {{_, status, _}, _headers, body}} ->
        {:error, {:http_error, status, body}}

      {:error, reason} ->
        {:error, reason}
    end
  end

  defp schedule_health_check do
    Process.send_after(self(), :health_check, @health_check_interval_ms)
  end

  defp schedule_restart(state) do
    cancel_timer(state.health_timer)
    delay = restart_delay(state.restart_count)

    Logger.info("[KuriDaemon] Scheduling restart in #{delay}ms (attempt #{state.restart_count + 1})")

    timer = Process.send_after(self(), :start_daemon, delay)

    {:noreply,
     %{
       state
       | status: :stopped,
         daemon_ref: nil,
         daemon_pid: nil,
         os_pid: nil,
         health_timer: nil,
         restart_timer: timer,
         restart_count: state.restart_count + 1
     }}
  end

  # Exponential backoff: 5s, 10s, 20s, 40s, capped at 60s
  defp restart_delay(restart_count) do
    delay = @base_restart_delay_ms * :math.pow(2, restart_count) |> round()
    min(delay, @max_restart_delay_ms)
  end

  defp cancel_timer(nil), do: :ok
  defp cancel_timer(ref), do: Process.cancel_timer(ref)

  # Kill the kuri daemon process. Tries OS-level kill first, falls back to
  # killing the Elixir spawn pid.
  defp kill_daemon(%{daemon_pid: nil}), do: :ok

  defp kill_daemon(state) do
    if state.daemon_ref do
      Process.demonitor(state.daemon_ref, [:flush])
    end

    # Try to find and kill the actual kuri OS process
    killed =
      case find_kuri_os_pid(state.port) do
        {:ok, os_pid} ->
          Logger.info("[KuriDaemon] Sending SIGTERM to kuri OS pid #{os_pid}")
          System.cmd("kill", ["-TERM", Integer.to_string(os_pid)], stderr_to_stdout: true)
          true

        :error ->
          false
      end

    unless killed do
      # Fallback: kill the Elixir process (which should terminate Exile stream)
      if Process.alive?(state.daemon_pid) do
        Process.exit(state.daemon_pid, :kill)
      end
    end

    :ok
  end

  # Find the OS pid of the kuri process listening on our port
  defp find_kuri_os_pid(port) do
    case System.cmd("lsof", ["-ti", ":#{port}"], stderr_to_stdout: true) do
      {output, 0} ->
        case output |> String.trim() |> String.split("\n") |> List.first() do
          nil -> :error
          "" -> :error
          pid_str ->
            case Integer.parse(pid_str) do
              {pid, _} -> {:ok, pid}
              :error -> :error
            end
        end

      _ ->
        :error
    end
  end

  defp check_existing_server(host, port) do
    url = "http://#{host}:#{port}/health"

    case :httpc.request(:get, {to_charlist(url), []}, [timeout: 2_000], body_format: :binary) do
      {:ok, {{_, 200, _}, _headers, body}} ->
        # Server is already running and healthy
        {:ok, body}

      {:ok, {{_, status, _}, _headers, _body}} ->
        # Port is in use but not healthy
        {:error, {:port_in_use, status}}

      {:error, _reason} ->
        # No server running on this port
        {:error, :no_server}
    end
  end

  defp read_token_file do
    path = Path.join([System.user_home!(), ".kuri", "api.token"])

    case File.read(path) do
      {:ok, content} -> String.trim(content)
      {:error, _} -> nil
    end
  end
end
